// Import necessary fonts
import { Inter } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";

// Import global styles
import "./globals.css";

// Import components
//import Navbar from "../components/Navbar"; // ✅ Ensure this file exists
// import TopicList from "../app/TopicList/page";
import dynamic from "next/dynamic";

//const TopicList = dynamic(() => import("../app/components/TopicList/page"));

// Initialize fonts
const inter = Inter({ subsets: ["latin"] });
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

// Metadata for the app
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="max-w-3xl mx-auto p-4">
          {/* <Navbar /> ✅ Ensure this component is correctly defined */}
          <div className="mt-8">{children}</div>
        </div>
      </body>
    </html>
  );
}
