
import { Inter } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import dynamic from "next/dynamic";
const inter = Inter({ subsets: ["latin"] });
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="max-w-3xl mx-auto p-4">
          {/* <Navbar />  */}
          <div className="mt-8">{children}</div>
        </div>
      </body>
    </html>
  );
}
